version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - ./local.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  django-app:
    env_file:
      - ./local.env
    environment:
      - POSTGRES_HOST=postgres
    build: ./django
    volumes:
      - ./django:/app
    ports:
      - 8000:8000
    image: django-app
    depends_on:
      - postgres
