version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - ./dev.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # sudo chown -R 5050:5050 ./data/pgadmin
  pgadmin:
    env_file:
      - ./dev.env
    image: dpage/pgadmin4
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80

  backend:
    env_file:
      - ./dev.env
    environment:
      - POSTGRES_HOST=postgres
      - WAIT_HOSTS=postgres:5432
    build:
      context: ./backend
      args:
        - MODE=dev
    volumes:
      - ./backend:/app
      - django_static:/app/static
      - django_media:/app/media
    ports:
      - 8000:8000
    image: backend:dev
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        - MODE=dev
    volumes:
      - ./frontend:/app
    image: frontend:dev
    ports:
      - 3000:80

  nginx:
    image: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - django_static:/var/www/django_static
      - django_media:/var/www/django_media
    depends_on:
      - backend
      - frontend

volumes:
  django_static:
  django_media:
