# Generated by Django 4.0.5 on 2022-06-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_city_city_name_rename_weather_weather_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weatherday',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='weatherday',
            unique_together={('city', 'day_number')},
        ),
        migrations.RemoveField(
            model_name='weatherday',
            name='weather',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
