# Generated by Django 4.0.5 on 2022-06-14 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weatherday_unique_together_weatherday_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherhour',
            name='cloud',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('icon', 'text')},
            },
        ),
        migrations.AddField(
            model_name='weatherhour',
            name='weather_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weathercondition'),
        ),
    ]
