# Generated by Django 4.0.5 on 2022-06-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weatherday_date_weatherhour_cloud_weathercondition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherhour',
            name='condition',
        ),
    ]
