# Generated by Django 4.0.5 on 2022-06-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherday',
            name='maxtemp_c',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherday',
            name='mintemp_c',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherday',
            name='weather_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weathercondition'),
        ),
    ]
