# Generated by Django 4.0.5 on 2022-06-16 11:07

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        CITextExtension(),
    ]
